/* Generated by DBCC, see <https://github.com/howerj/dbcc> */
#include "MDU_V002x_TB.h"
#include <inttypes.h>
#include <assert.h>

#define UNUSED(X) ((void)(X))

static inline uint64_t reverse_byte_order(uint64_t x) {
	x = (x & 0x00000000FFFFFFFF) << 32 | (x & 0xFFFFFFFF00000000) >> 32;
	x = (x & 0x0000FFFF0000FFFF) << 16 | (x & 0xFFFF0000FFFF0000) >> 16;
	x = (x & 0x00FF00FF00FF00FF) << 8  | (x & 0xFF00FF00FF00FF00) >> 8;
	return x;
}

static inline int print_helper(int r, int print_return_value) {
	return ((r >= 0) && (print_return_value >= 0)) ? r + print_return_value : -1;
}

static int pack_can_0x109_VCU_Engine_Torque_EPP(can_obj_mdu_v002x_tb_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t m = 0;
	/* VCU_Eng_Req_Torque: start-bit 7, length 16, endianess motorola, scaling 0.05, offset 0 */
	x = ((uint16_t)(o->can_0x109_VCU_Engine_Torque_EPP.VCU_Eng_Req_Torque)) & 0xffff;
	x <<= 48; 
	m |= x;
	/* VCU_CRC_109: start-bit 60, length 5, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x109_VCU_Engine_Torque_EPP.VCU_CRC_109)) & 0x1f;
	m |= x;
	/* VCU_Alive_Counter_109: start-bit 63, length 3, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x109_VCU_Engine_Torque_EPP.VCU_Alive_Counter_109)) & 0x7;
	x <<= 5; 
	m |= x;
	/* VCU_Engine_Direction_Req: start-bit 22, length 2, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x109_VCU_Engine_Torque_EPP.VCU_Engine_Direction_Req)) & 0x3;
	x <<= 45; 
	m |= x;
	/* VCU_Eng_Req_Torque_Valid: start-bit 20, length 1, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x109_VCU_Engine_Torque_EPP.VCU_Eng_Req_Torque_Valid)) & 0x1;
	x <<= 44; 
	m |= x;
	/* VCU_MDU_Interlock: start-bit 23, length 1, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x109_VCU_Engine_Torque_EPP.VCU_MDU_Interlock)) & 0x1;
	x <<= 47; 
	m |= x;
	*data = reverse_byte_order(m);
	o->can_0x109_VCU_Engine_Torque_EPP_tx = 1;
	return 8;
}

static int unpack_can_0x109_VCU_Engine_Torque_EPP(can_obj_mdu_v002x_tb_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t m = reverse_byte_order(data);
	if (dlc < 8)
		return -1;
	/* VCU_Eng_Req_Torque: start-bit 7, length 16, endianess motorola, scaling 0.05, offset 0 */
	x = (m >> 48) & 0xffff;
	o->can_0x109_VCU_Engine_Torque_EPP.VCU_Eng_Req_Torque = x;
	/* VCU_CRC_109: start-bit 60, length 5, endianess motorola, scaling 1, offset 0 */
	x = m & 0x1f;
	o->can_0x109_VCU_Engine_Torque_EPP.VCU_CRC_109 = x;
	/* VCU_Alive_Counter_109: start-bit 63, length 3, endianess motorola, scaling 1, offset 0 */
	x = (m >> 5) & 0x7;
	o->can_0x109_VCU_Engine_Torque_EPP.VCU_Alive_Counter_109 = x;
	/* VCU_Engine_Direction_Req: start-bit 22, length 2, endianess motorola, scaling 1, offset 0 */
	x = (m >> 45) & 0x3;
	o->can_0x109_VCU_Engine_Torque_EPP.VCU_Engine_Direction_Req = x;
	/* VCU_Eng_Req_Torque_Valid: start-bit 20, length 1, endianess motorola, scaling 1, offset 0 */
	x = (m >> 44) & 0x1;
	o->can_0x109_VCU_Engine_Torque_EPP.VCU_Eng_Req_Torque_Valid = x;
	/* VCU_MDU_Interlock: start-bit 23, length 1, endianess motorola, scaling 1, offset 0 */
	x = (m >> 47) & 0x1;
	o->can_0x109_VCU_Engine_Torque_EPP.VCU_MDU_Interlock = x;
	o->can_0x109_VCU_Engine_Torque_EPP_rx = 1;
	o->can_0x109_VCU_Engine_Torque_EPP_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x109_VCU_Eng_Req_Torque(const can_obj_mdu_v002x_tb_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x109_VCU_Engine_Torque_EPP.VCU_Eng_Req_Torque);
	rval *= 0.05;
	if ((rval >= -1000) && (rval <= 1000)) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x109_VCU_Eng_Req_Torque(can_obj_mdu_v002x_tb_h_t *o, double in) {
	assert(o);
	o->can_0x109_VCU_Engine_Torque_EPP.VCU_Eng_Req_Torque = 0;
	if (in < -1000)
		return -1;
	if (in > 1000)
		return -1;
	in *= 20;
	o->can_0x109_VCU_Engine_Torque_EPP.VCU_Eng_Req_Torque = in;
	return 0;
}

int decode_can_0x109_VCU_CRC_109(const can_obj_mdu_v002x_tb_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x109_VCU_Engine_Torque_EPP.VCU_CRC_109);
	*out = rval;
	return 0;
}

int encode_can_0x109_VCU_CRC_109(can_obj_mdu_v002x_tb_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x109_VCU_Engine_Torque_EPP.VCU_CRC_109 = in;
	return 0;
}

int decode_can_0x109_VCU_Alive_Counter_109(const can_obj_mdu_v002x_tb_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x109_VCU_Engine_Torque_EPP.VCU_Alive_Counter_109);
	if (rval <= 6) {
		*out = rval;
		return 0;
	} else {
		*out = (uint8_t)0;
		return -1;
	}
}

int encode_can_0x109_VCU_Alive_Counter_109(can_obj_mdu_v002x_tb_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x109_VCU_Engine_Torque_EPP.VCU_Alive_Counter_109 = 0;
	if (in > 6)
		return -1;
	o->can_0x109_VCU_Engine_Torque_EPP.VCU_Alive_Counter_109 = in;
	return 0;
}

int decode_can_0x109_VCU_Engine_Direction_Req(const can_obj_mdu_v002x_tb_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x109_VCU_Engine_Torque_EPP.VCU_Engine_Direction_Req);
	*out = rval;
	return 0;
}

int encode_can_0x109_VCU_Engine_Direction_Req(can_obj_mdu_v002x_tb_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x109_VCU_Engine_Torque_EPP.VCU_Engine_Direction_Req = in;
	return 0;
}

int decode_can_0x109_VCU_Eng_Req_Torque_Valid(const can_obj_mdu_v002x_tb_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x109_VCU_Engine_Torque_EPP.VCU_Eng_Req_Torque_Valid);
	*out = rval;
	return 0;
}

int encode_can_0x109_VCU_Eng_Req_Torque_Valid(can_obj_mdu_v002x_tb_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x109_VCU_Engine_Torque_EPP.VCU_Eng_Req_Torque_Valid = in;
	return 0;
}

int decode_can_0x109_VCU_MDU_Interlock(const can_obj_mdu_v002x_tb_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x109_VCU_Engine_Torque_EPP.VCU_MDU_Interlock);
	*out = rval;
	return 0;
}

int encode_can_0x109_VCU_MDU_Interlock(can_obj_mdu_v002x_tb_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x109_VCU_Engine_Torque_EPP.VCU_MDU_Interlock = in;
	return 0;
}

int print_can_0x109_VCU_Engine_Torque_EPP(const can_obj_mdu_v002x_tb_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "VCU_Eng_Req_Torque = (wire: %.0f)\n", (double)(o->can_0x109_VCU_Engine_Torque_EPP.VCU_Eng_Req_Torque)));
	r = print_helper(r, fprintf(output, "VCU_CRC_109 = (wire: %.0f)\n", (double)(o->can_0x109_VCU_Engine_Torque_EPP.VCU_CRC_109)));
	r = print_helper(r, fprintf(output, "VCU_Alive_Counter_109 = (wire: %.0f)\n", (double)(o->can_0x109_VCU_Engine_Torque_EPP.VCU_Alive_Counter_109)));
	r = print_helper(r, fprintf(output, "VCU_Engine_Direction_Req = (wire: %.0f)\n", (double)(o->can_0x109_VCU_Engine_Torque_EPP.VCU_Engine_Direction_Req)));
	r = print_helper(r, fprintf(output, "VCU_Eng_Req_Torque_Valid = (wire: %.0f)\n", (double)(o->can_0x109_VCU_Engine_Torque_EPP.VCU_Eng_Req_Torque_Valid)));
	r = print_helper(r, fprintf(output, "VCU_MDU_Interlock = (wire: %.0f)\n", (double)(o->can_0x109_VCU_Engine_Torque_EPP.VCU_MDU_Interlock)));
	return r;
}

static int pack_can_0x11a_MDU_Speed_Torque_Info(can_obj_mdu_v002x_tb_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t m = 0;
	/* MDU_Engine_Rpm: start-bit 7, length 16, endianess motorola, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x11a_MDU_Speed_Torque_Info.MDU_Engine_Rpm)) & 0xffff;
	x <<= 48; 
	m |= x;
	/* MDU_Eng_Act_RPM_Gradient: start-bit 23, length 16, endianess motorola, scaling 10, offset 0 */
	x = ((uint16_t)(o->can_0x11a_MDU_Speed_Torque_Info.MDU_Eng_Act_RPM_Gradient)) & 0xffff;
	x <<= 32; 
	m |= x;
	/* MDU_Eng_Actual_Torque: start-bit 47, length 16, endianess motorola, scaling 0.2, offset 0 */
	x = ((uint16_t)(o->can_0x11a_MDU_Speed_Torque_Info.MDU_Eng_Actual_Torque)) & 0xffff;
	x <<= 8; 
	m |= x;
	/* MDU_CRC_11A: start-bit 60, length 5, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x11a_MDU_Speed_Torque_Info.MDU_CRC_11A)) & 0x1f;
	m |= x;
	/* MDU_Alive_Counter_11A: start-bit 63, length 3, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x11a_MDU_Speed_Torque_Info.MDU_Alive_Counter_11A)) & 0x7;
	x <<= 5; 
	m |= x;
	/* MDU_Engine_Rpm_Validity: start-bit 38, length 1, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x11a_MDU_Speed_Torque_Info.MDU_Engine_Rpm_Validity)) & 0x1;
	x <<= 30; 
	m |= x;
	/* MDU_Eng_Act_Trq_Validity: start-bit 39, length 1, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x11a_MDU_Speed_Torque_Info.MDU_Eng_Act_Trq_Validity)) & 0x1;
	x <<= 31; 
	m |= x;
	*data = reverse_byte_order(m);
	o->can_0x11a_MDU_Speed_Torque_Info_tx = 1;
	return 8;
}

static int unpack_can_0x11a_MDU_Speed_Torque_Info(can_obj_mdu_v002x_tb_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t m = reverse_byte_order(data);
	if (dlc < 8)
		return -1;
	/* MDU_Engine_Rpm: start-bit 7, length 16, endianess motorola, scaling 1, offset 0 */
	x = (m >> 48) & 0xffff;
	o->can_0x11a_MDU_Speed_Torque_Info.MDU_Engine_Rpm = x;
	/* MDU_Eng_Act_RPM_Gradient: start-bit 23, length 16, endianess motorola, scaling 10, offset 0 */
	x = (m >> 32) & 0xffff;
	o->can_0x11a_MDU_Speed_Torque_Info.MDU_Eng_Act_RPM_Gradient = x;
	/* MDU_Eng_Actual_Torque: start-bit 47, length 16, endianess motorola, scaling 0.2, offset 0 */
	x = (m >> 8) & 0xffff;
	o->can_0x11a_MDU_Speed_Torque_Info.MDU_Eng_Actual_Torque = x;
	/* MDU_CRC_11A: start-bit 60, length 5, endianess motorola, scaling 1, offset 0 */
	x = m & 0x1f;
	o->can_0x11a_MDU_Speed_Torque_Info.MDU_CRC_11A = x;
	/* MDU_Alive_Counter_11A: start-bit 63, length 3, endianess motorola, scaling 1, offset 0 */
	x = (m >> 5) & 0x7;
	o->can_0x11a_MDU_Speed_Torque_Info.MDU_Alive_Counter_11A = x;
	/* MDU_Engine_Rpm_Validity: start-bit 38, length 1, endianess motorola, scaling 1, offset 0 */
	x = (m >> 30) & 0x1;
	o->can_0x11a_MDU_Speed_Torque_Info.MDU_Engine_Rpm_Validity = x;
	/* MDU_Eng_Act_Trq_Validity: start-bit 39, length 1, endianess motorola, scaling 1, offset 0 */
	x = (m >> 31) & 0x1;
	o->can_0x11a_MDU_Speed_Torque_Info.MDU_Eng_Act_Trq_Validity = x;
	o->can_0x11a_MDU_Speed_Torque_Info_rx = 1;
	o->can_0x11a_MDU_Speed_Torque_Info_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x11a_MDU_Engine_Rpm(const can_obj_mdu_v002x_tb_h_t *o, int16_t *out) {
	assert(o);
	assert(out);
	int16_t rval = (int16_t)(o->can_0x11a_MDU_Speed_Torque_Info.MDU_Engine_Rpm);
	if ((rval >= -20000) && (rval <= 20000)) {
		*out = rval;
		return 0;
	} else {
		*out = (int16_t)0;
		return -1;
	}
}

int encode_can_0x11a_MDU_Engine_Rpm(can_obj_mdu_v002x_tb_h_t *o, int16_t in) {
	assert(o);
	o->can_0x11a_MDU_Speed_Torque_Info.MDU_Engine_Rpm = 0;
	if (in < -20000)
		return -1;
	if (in > 20000)
		return -1;
	o->can_0x11a_MDU_Speed_Torque_Info.MDU_Engine_Rpm = in;
	return 0;
}

int decode_can_0x11a_MDU_Eng_Act_RPM_Gradient(const can_obj_mdu_v002x_tb_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x11a_MDU_Speed_Torque_Info.MDU_Eng_Act_RPM_Gradient);
	rval *= 10;
	*out = rval;
	return 0;
}

int encode_can_0x11a_MDU_Eng_Act_RPM_Gradient(can_obj_mdu_v002x_tb_h_t *o, double in) {
	assert(o);
	in *= 0.1;
	o->can_0x11a_MDU_Speed_Torque_Info.MDU_Eng_Act_RPM_Gradient = in;
	return 0;
}

int decode_can_0x11a_MDU_Eng_Actual_Torque(const can_obj_mdu_v002x_tb_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x11a_MDU_Speed_Torque_Info.MDU_Eng_Actual_Torque);
	rval *= 0.2;
	if ((rval >= -1000) && (rval <= 1000)) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x11a_MDU_Eng_Actual_Torque(can_obj_mdu_v002x_tb_h_t *o, double in) {
	assert(o);
	o->can_0x11a_MDU_Speed_Torque_Info.MDU_Eng_Actual_Torque = 0;
	if (in < -1000)
		return -1;
	if (in > 1000)
		return -1;
	in *= 5;
	o->can_0x11a_MDU_Speed_Torque_Info.MDU_Eng_Actual_Torque = in;
	return 0;
}

int decode_can_0x11a_MDU_CRC_11A(const can_obj_mdu_v002x_tb_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x11a_MDU_Speed_Torque_Info.MDU_CRC_11A);
	*out = rval;
	return 0;
}

int encode_can_0x11a_MDU_CRC_11A(can_obj_mdu_v002x_tb_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x11a_MDU_Speed_Torque_Info.MDU_CRC_11A = in;
	return 0;
}

int decode_can_0x11a_MDU_Alive_Counter_11A(const can_obj_mdu_v002x_tb_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x11a_MDU_Speed_Torque_Info.MDU_Alive_Counter_11A);
	if (rval <= 6) {
		*out = rval;
		return 0;
	} else {
		*out = (uint8_t)0;
		return -1;
	}
}

int encode_can_0x11a_MDU_Alive_Counter_11A(can_obj_mdu_v002x_tb_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x11a_MDU_Speed_Torque_Info.MDU_Alive_Counter_11A = 0;
	if (in > 6)
		return -1;
	o->can_0x11a_MDU_Speed_Torque_Info.MDU_Alive_Counter_11A = in;
	return 0;
}

int decode_can_0x11a_MDU_Engine_Rpm_Validity(const can_obj_mdu_v002x_tb_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x11a_MDU_Speed_Torque_Info.MDU_Engine_Rpm_Validity);
	*out = rval;
	return 0;
}

int encode_can_0x11a_MDU_Engine_Rpm_Validity(can_obj_mdu_v002x_tb_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x11a_MDU_Speed_Torque_Info.MDU_Engine_Rpm_Validity = in;
	return 0;
}

int decode_can_0x11a_MDU_Eng_Act_Trq_Validity(const can_obj_mdu_v002x_tb_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x11a_MDU_Speed_Torque_Info.MDU_Eng_Act_Trq_Validity);
	*out = rval;
	return 0;
}

int encode_can_0x11a_MDU_Eng_Act_Trq_Validity(can_obj_mdu_v002x_tb_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x11a_MDU_Speed_Torque_Info.MDU_Eng_Act_Trq_Validity = in;
	return 0;
}

int print_can_0x11a_MDU_Speed_Torque_Info(const can_obj_mdu_v002x_tb_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "MDU_Engine_Rpm = (wire: %.0f)\n", (double)(o->can_0x11a_MDU_Speed_Torque_Info.MDU_Engine_Rpm)));
	r = print_helper(r, fprintf(output, "MDU_Eng_Act_RPM_Gradient = (wire: %.0f)\n", (double)(o->can_0x11a_MDU_Speed_Torque_Info.MDU_Eng_Act_RPM_Gradient)));
	r = print_helper(r, fprintf(output, "MDU_Eng_Actual_Torque = (wire: %.0f)\n", (double)(o->can_0x11a_MDU_Speed_Torque_Info.MDU_Eng_Actual_Torque)));
	r = print_helper(r, fprintf(output, "MDU_CRC_11A = (wire: %.0f)\n", (double)(o->can_0x11a_MDU_Speed_Torque_Info.MDU_CRC_11A)));
	r = print_helper(r, fprintf(output, "MDU_Alive_Counter_11A = (wire: %.0f)\n", (double)(o->can_0x11a_MDU_Speed_Torque_Info.MDU_Alive_Counter_11A)));
	r = print_helper(r, fprintf(output, "MDU_Engine_Rpm_Validity = (wire: %.0f)\n", (double)(o->can_0x11a_MDU_Speed_Torque_Info.MDU_Engine_Rpm_Validity)));
	r = print_helper(r, fprintf(output, "MDU_Eng_Act_Trq_Validity = (wire: %.0f)\n", (double)(o->can_0x11a_MDU_Speed_Torque_Info.MDU_Eng_Act_Trq_Validity)));
	return r;
}

static int pack_can_0x11b_MDU_Status_Info_1(can_obj_mdu_v002x_tb_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t m = 0;
	/* MDU_Max_Torque_Avl: start-bit 7, length 12, endianess motorola, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x11b_MDU_Status_Info_1.MDU_Max_Torque_Avl)) & 0xfff;
	x <<= 52; 
	m |= x;
	/* MDU_Min_Torque_Avl: start-bit 11, length 12, endianess motorola, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x11b_MDU_Status_Info_1.MDU_Min_Torque_Avl)) & 0xfff;
	x <<= 40; 
	m |= x;
	/* MDU_Max_Torque_Derating: start-bit 31, length 12, endianess motorola, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x11b_MDU_Status_Info_1.MDU_Max_Torque_Derating)) & 0xfff;
	x <<= 28; 
	m |= x;
	/* MDU_Min_Torque_Derating: start-bit 35, length 12, endianess motorola, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x11b_MDU_Status_Info_1.MDU_Min_Torque_Derating)) & 0xfff;
	x <<= 16; 
	m |= x;
	*data = reverse_byte_order(m);
	o->can_0x11b_MDU_Status_Info_1_tx = 1;
	return 8;
}

static int unpack_can_0x11b_MDU_Status_Info_1(can_obj_mdu_v002x_tb_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t m = reverse_byte_order(data);
	if (dlc < 8)
		return -1;
	/* MDU_Max_Torque_Avl: start-bit 7, length 12, endianess motorola, scaling 0.1, offset 0 */
	x = (m >> 52) & 0xfff;
	x = (x & 0x800) ? (x | 0xf000) : x; 
	o->can_0x11b_MDU_Status_Info_1.MDU_Max_Torque_Avl = x;
	/* MDU_Min_Torque_Avl: start-bit 11, length 12, endianess motorola, scaling 0.1, offset 0 */
	x = (m >> 40) & 0xfff;
	x = (x & 0x800) ? (x | 0xf000) : x; 
	o->can_0x11b_MDU_Status_Info_1.MDU_Min_Torque_Avl = x;
	/* MDU_Max_Torque_Derating: start-bit 31, length 12, endianess motorola, scaling 0.1, offset 0 */
	x = (m >> 28) & 0xfff;
	x = (x & 0x800) ? (x | 0xf000) : x; 
	o->can_0x11b_MDU_Status_Info_1.MDU_Max_Torque_Derating = x;
	/* MDU_Min_Torque_Derating: start-bit 35, length 12, endianess motorola, scaling 0.1, offset 0 */
	x = (m >> 16) & 0xfff;
	x = (x & 0x800) ? (x | 0xf000) : x; 
	o->can_0x11b_MDU_Status_Info_1.MDU_Min_Torque_Derating = x;
	o->can_0x11b_MDU_Status_Info_1_rx = 1;
	o->can_0x11b_MDU_Status_Info_1_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x11b_MDU_Max_Torque_Avl(const can_obj_mdu_v002x_tb_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x11b_MDU_Status_Info_1.MDU_Max_Torque_Avl);
	rval *= 0.1;
	if ((rval >= -204.8) && (rval <= 204.7)) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x11b_MDU_Max_Torque_Avl(can_obj_mdu_v002x_tb_h_t *o, double in) {
	assert(o);
	o->can_0x11b_MDU_Status_Info_1.MDU_Max_Torque_Avl = 0;
	if (in < -204.8)
		return -1;
	if (in > 204.7)
		return -1;
	in *= 10;
	o->can_0x11b_MDU_Status_Info_1.MDU_Max_Torque_Avl = in;
	return 0;
}

int decode_can_0x11b_MDU_Min_Torque_Avl(const can_obj_mdu_v002x_tb_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x11b_MDU_Status_Info_1.MDU_Min_Torque_Avl);
	rval *= 0.1;
	if ((rval >= -204.8) && (rval <= 204.7)) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x11b_MDU_Min_Torque_Avl(can_obj_mdu_v002x_tb_h_t *o, double in) {
	assert(o);
	o->can_0x11b_MDU_Status_Info_1.MDU_Min_Torque_Avl = 0;
	if (in < -204.8)
		return -1;
	if (in > 204.7)
		return -1;
	in *= 10;
	o->can_0x11b_MDU_Status_Info_1.MDU_Min_Torque_Avl = in;
	return 0;
}

int decode_can_0x11b_MDU_Max_Torque_Derating(const can_obj_mdu_v002x_tb_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x11b_MDU_Status_Info_1.MDU_Max_Torque_Derating);
	rval *= 0.1;
	if ((rval >= -204.8) && (rval <= 204.7)) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x11b_MDU_Max_Torque_Derating(can_obj_mdu_v002x_tb_h_t *o, double in) {
	assert(o);
	o->can_0x11b_MDU_Status_Info_1.MDU_Max_Torque_Derating = 0;
	if (in < -204.8)
		return -1;
	if (in > 204.7)
		return -1;
	in *= 10;
	o->can_0x11b_MDU_Status_Info_1.MDU_Max_Torque_Derating = in;
	return 0;
}

int decode_can_0x11b_MDU_Min_Torque_Derating(const can_obj_mdu_v002x_tb_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x11b_MDU_Status_Info_1.MDU_Min_Torque_Derating);
	rval *= 0.1;
	if ((rval >= -204.8) && (rval <= 204.7)) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x11b_MDU_Min_Torque_Derating(can_obj_mdu_v002x_tb_h_t *o, double in) {
	assert(o);
	o->can_0x11b_MDU_Status_Info_1.MDU_Min_Torque_Derating = 0;
	if (in < -204.8)
		return -1;
	if (in > 204.7)
		return -1;
	in *= 10;
	o->can_0x11b_MDU_Status_Info_1.MDU_Min_Torque_Derating = in;
	return 0;
}

int print_can_0x11b_MDU_Status_Info_1(const can_obj_mdu_v002x_tb_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "MDU_Max_Torque_Avl = (wire: %.0f)\n", (double)(o->can_0x11b_MDU_Status_Info_1.MDU_Max_Torque_Avl)));
	r = print_helper(r, fprintf(output, "MDU_Min_Torque_Avl = (wire: %.0f)\n", (double)(o->can_0x11b_MDU_Status_Info_1.MDU_Min_Torque_Avl)));
	r = print_helper(r, fprintf(output, "MDU_Max_Torque_Derating = (wire: %.0f)\n", (double)(o->can_0x11b_MDU_Status_Info_1.MDU_Max_Torque_Derating)));
	r = print_helper(r, fprintf(output, "MDU_Min_Torque_Derating = (wire: %.0f)\n", (double)(o->can_0x11b_MDU_Status_Info_1.MDU_Min_Torque_Derating)));
	return r;
}

static int pack_can_0x11f_VCU_EPP_Data(can_obj_mdu_v002x_tb_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t m = 0;
	/* VCU_CRC_11F: start-bit 60, length 5, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x11f_VCU_EPP_Data.VCU_CRC_11F)) & 0x1f;
	m |= x;
	/* VCU_Vehicle_State: start-bit 31, length 4, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x11f_VCU_EPP_Data.VCU_Vehicle_State)) & 0xf;
	x <<= 36; 
	m |= x;
	/* VCU_Regen_Mode_Response: start-bit 18, length 3, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x11f_VCU_EPP_Data.VCU_Regen_Mode_Response)) & 0x7;
	x <<= 40; 
	m |= x;
	/* VCU_Alive_Counter_11F: start-bit 63, length 3, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x11f_VCU_EPP_Data.VCU_Alive_Counter_11F)) & 0x7;
	x <<= 5; 
	m |= x;
	/* VCU_Drive_Mode_Status: start-bit 27, length 2, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x11f_VCU_EPP_Data.VCU_Drive_Mode_Status)) & 0x3;
	x <<= 34; 
	m |= x;
	/* VCU_TC_Status_Response: start-bit 55, length 1, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x11f_VCU_EPP_Data.VCU_TC_Status_Response)) & 0x1;
	x <<= 15; 
	m |= x;
	*data = reverse_byte_order(m);
	o->can_0x11f_VCU_EPP_Data_tx = 1;
	return 8;
}

static int unpack_can_0x11f_VCU_EPP_Data(can_obj_mdu_v002x_tb_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t m = reverse_byte_order(data);
	if (dlc < 8)
		return -1;
	/* VCU_CRC_11F: start-bit 60, length 5, endianess motorola, scaling 1, offset 0 */
	x = m & 0x1f;
	o->can_0x11f_VCU_EPP_Data.VCU_CRC_11F = x;
	/* VCU_Vehicle_State: start-bit 31, length 4, endianess motorola, scaling 1, offset 0 */
	x = (m >> 36) & 0xf;
	o->can_0x11f_VCU_EPP_Data.VCU_Vehicle_State = x;
	/* VCU_Regen_Mode_Response: start-bit 18, length 3, endianess motorola, scaling 1, offset 0 */
	x = (m >> 40) & 0x7;
	o->can_0x11f_VCU_EPP_Data.VCU_Regen_Mode_Response = x;
	/* VCU_Alive_Counter_11F: start-bit 63, length 3, endianess motorola, scaling 1, offset 0 */
	x = (m >> 5) & 0x7;
	o->can_0x11f_VCU_EPP_Data.VCU_Alive_Counter_11F = x;
	/* VCU_Drive_Mode_Status: start-bit 27, length 2, endianess motorola, scaling 1, offset 0 */
	x = (m >> 34) & 0x3;
	o->can_0x11f_VCU_EPP_Data.VCU_Drive_Mode_Status = x;
	/* VCU_TC_Status_Response: start-bit 55, length 1, endianess motorola, scaling 1, offset 0 */
	x = (m >> 15) & 0x1;
	o->can_0x11f_VCU_EPP_Data.VCU_TC_Status_Response = x;
	o->can_0x11f_VCU_EPP_Data_rx = 1;
	o->can_0x11f_VCU_EPP_Data_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x11f_VCU_CRC_11F(const can_obj_mdu_v002x_tb_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x11f_VCU_EPP_Data.VCU_CRC_11F);
	*out = rval;
	return 0;
}

int encode_can_0x11f_VCU_CRC_11F(can_obj_mdu_v002x_tb_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x11f_VCU_EPP_Data.VCU_CRC_11F = in;
	return 0;
}

int decode_can_0x11f_VCU_Vehicle_State(const can_obj_mdu_v002x_tb_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x11f_VCU_EPP_Data.VCU_Vehicle_State);
	*out = rval;
	return 0;
}

int encode_can_0x11f_VCU_Vehicle_State(can_obj_mdu_v002x_tb_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x11f_VCU_EPP_Data.VCU_Vehicle_State = in;
	return 0;
}

int decode_can_0x11f_VCU_Regen_Mode_Response(const can_obj_mdu_v002x_tb_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x11f_VCU_EPP_Data.VCU_Regen_Mode_Response);
	*out = rval;
	return 0;
}

int encode_can_0x11f_VCU_Regen_Mode_Response(can_obj_mdu_v002x_tb_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x11f_VCU_EPP_Data.VCU_Regen_Mode_Response = in;
	return 0;
}

int decode_can_0x11f_VCU_Alive_Counter_11F(const can_obj_mdu_v002x_tb_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x11f_VCU_EPP_Data.VCU_Alive_Counter_11F);
	if (rval <= 6) {
		*out = rval;
		return 0;
	} else {
		*out = (uint8_t)0;
		return -1;
	}
}

int encode_can_0x11f_VCU_Alive_Counter_11F(can_obj_mdu_v002x_tb_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x11f_VCU_EPP_Data.VCU_Alive_Counter_11F = 0;
	if (in > 6)
		return -1;
	o->can_0x11f_VCU_EPP_Data.VCU_Alive_Counter_11F = in;
	return 0;
}

int decode_can_0x11f_VCU_Drive_Mode_Status(const can_obj_mdu_v002x_tb_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x11f_VCU_EPP_Data.VCU_Drive_Mode_Status);
	*out = rval;
	return 0;
}

int encode_can_0x11f_VCU_Drive_Mode_Status(can_obj_mdu_v002x_tb_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x11f_VCU_EPP_Data.VCU_Drive_Mode_Status = in;
	return 0;
}

int decode_can_0x11f_VCU_TC_Status_Response(const can_obj_mdu_v002x_tb_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x11f_VCU_EPP_Data.VCU_TC_Status_Response);
	*out = rval;
	return 0;
}

int encode_can_0x11f_VCU_TC_Status_Response(can_obj_mdu_v002x_tb_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x11f_VCU_EPP_Data.VCU_TC_Status_Response = in;
	return 0;
}

int print_can_0x11f_VCU_EPP_Data(const can_obj_mdu_v002x_tb_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "VCU_CRC_11F = (wire: %.0f)\n", (double)(o->can_0x11f_VCU_EPP_Data.VCU_CRC_11F)));
	r = print_helper(r, fprintf(output, "VCU_Vehicle_State = (wire: %.0f)\n", (double)(o->can_0x11f_VCU_EPP_Data.VCU_Vehicle_State)));
	r = print_helper(r, fprintf(output, "VCU_Regen_Mode_Response = (wire: %.0f)\n", (double)(o->can_0x11f_VCU_EPP_Data.VCU_Regen_Mode_Response)));
	r = print_helper(r, fprintf(output, "VCU_Alive_Counter_11F = (wire: %.0f)\n", (double)(o->can_0x11f_VCU_EPP_Data.VCU_Alive_Counter_11F)));
	r = print_helper(r, fprintf(output, "VCU_Drive_Mode_Status = (wire: %.0f)\n", (double)(o->can_0x11f_VCU_EPP_Data.VCU_Drive_Mode_Status)));
	r = print_helper(r, fprintf(output, "VCU_TC_Status_Response = (wire: %.0f)\n", (double)(o->can_0x11f_VCU_EPP_Data.VCU_TC_Status_Response)));
	return r;
}

static int pack_can_0x152_BMS_Pack_CV_Info(can_obj_mdu_v002x_tb_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t m = 0;
	/* BMS_Current_Pack: start-bit 7, length 16, endianess motorola, scaling 0.2, offset 0 */
	x = ((uint16_t)(o->can_0x152_BMS_Pack_CV_Info.BMS_Current_Pack)) & 0xffff;
	x <<= 48; 
	m |= x;
	/* BMS_Voltage_Pack: start-bit 23, length 13, endianess motorola, scaling 0.075, offset 0 */
	x = ((uint16_t)(o->can_0x152_BMS_Pack_CV_Info.BMS_Voltage_Pack)) & 0x1fff;
	x <<= 35; 
	m |= x;
	/* DASH_CRC_152: start-bit 60, length 5, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x152_BMS_Pack_CV_Info.DASH_CRC_152)) & 0x1f;
	m |= x;
	/* DASH_Alive_Counter_152: start-bit 63, length 3, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x152_BMS_Pack_CV_Info.DASH_Alive_Counter_152)) & 0x7;
	x <<= 5; 
	m |= x;
	/* BMS_Regeneration_Allowed: start-bit 24, length 1, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x152_BMS_Pack_CV_Info.BMS_Regeneration_Allowed)) & 0x1;
	x <<= 32; 
	m |= x;
	/* BMS_Status_FET: start-bit 25, length 1, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x152_BMS_Pack_CV_Info.BMS_Status_FET)) & 0x1;
	x <<= 33; 
	m |= x;
	*data = reverse_byte_order(m);
	o->can_0x152_BMS_Pack_CV_Info_tx = 1;
	return 8;
}

static int unpack_can_0x152_BMS_Pack_CV_Info(can_obj_mdu_v002x_tb_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t m = reverse_byte_order(data);
	if (dlc < 8)
		return -1;
	/* BMS_Current_Pack: start-bit 7, length 16, endianess motorola, scaling 0.2, offset 0 */
	x = (m >> 48) & 0xffff;
	o->can_0x152_BMS_Pack_CV_Info.BMS_Current_Pack = x;
	/* BMS_Voltage_Pack: start-bit 23, length 13, endianess motorola, scaling 0.075, offset 0 */
	x = (m >> 35) & 0x1fff;
	o->can_0x152_BMS_Pack_CV_Info.BMS_Voltage_Pack = x;
	/* DASH_CRC_152: start-bit 60, length 5, endianess motorola, scaling 1, offset 0 */
	x = m & 0x1f;
	o->can_0x152_BMS_Pack_CV_Info.DASH_CRC_152 = x;
	/* DASH_Alive_Counter_152: start-bit 63, length 3, endianess motorola, scaling 1, offset 0 */
	x = (m >> 5) & 0x7;
	o->can_0x152_BMS_Pack_CV_Info.DASH_Alive_Counter_152 = x;
	/* BMS_Regeneration_Allowed: start-bit 24, length 1, endianess motorola, scaling 1, offset 0 */
	x = (m >> 32) & 0x1;
	o->can_0x152_BMS_Pack_CV_Info.BMS_Regeneration_Allowed = x;
	/* BMS_Status_FET: start-bit 25, length 1, endianess motorola, scaling 1, offset 0 */
	x = (m >> 33) & 0x1;
	o->can_0x152_BMS_Pack_CV_Info.BMS_Status_FET = x;
	o->can_0x152_BMS_Pack_CV_Info_rx = 1;
	o->can_0x152_BMS_Pack_CV_Info_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x152_BMS_Current_Pack(const can_obj_mdu_v002x_tb_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x152_BMS_Pack_CV_Info.BMS_Current_Pack);
	rval *= 0.2;
	if ((rval >= -1000) && (rval <= 1000)) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x152_BMS_Current_Pack(can_obj_mdu_v002x_tb_h_t *o, double in) {
	assert(o);
	o->can_0x152_BMS_Pack_CV_Info.BMS_Current_Pack = 0;
	if (in < -1000)
		return -1;
	if (in > 1000)
		return -1;
	in *= 5;
	o->can_0x152_BMS_Pack_CV_Info.BMS_Current_Pack = in;
	return 0;
}

int decode_can_0x152_BMS_Voltage_Pack(const can_obj_mdu_v002x_tb_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x152_BMS_Pack_CV_Info.BMS_Voltage_Pack);
	rval *= 0.075;
	if (rval <= 614.325) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x152_BMS_Voltage_Pack(can_obj_mdu_v002x_tb_h_t *o, double in) {
	assert(o);
	o->can_0x152_BMS_Pack_CV_Info.BMS_Voltage_Pack = 0;
	if (in > 614.325)
		return -1;
	in *= 13.3333;
	o->can_0x152_BMS_Pack_CV_Info.BMS_Voltage_Pack = in;
	return 0;
}

int decode_can_0x152_DASH_CRC_152(const can_obj_mdu_v002x_tb_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x152_BMS_Pack_CV_Info.DASH_CRC_152);
	*out = rval;
	return 0;
}

int encode_can_0x152_DASH_CRC_152(can_obj_mdu_v002x_tb_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x152_BMS_Pack_CV_Info.DASH_CRC_152 = in;
	return 0;
}

int decode_can_0x152_DASH_Alive_Counter_152(const can_obj_mdu_v002x_tb_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x152_BMS_Pack_CV_Info.DASH_Alive_Counter_152);
	if (rval <= 6) {
		*out = rval;
		return 0;
	} else {
		*out = (uint8_t)0;
		return -1;
	}
}

int encode_can_0x152_DASH_Alive_Counter_152(can_obj_mdu_v002x_tb_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x152_BMS_Pack_CV_Info.DASH_Alive_Counter_152 = 0;
	if (in > 6)
		return -1;
	o->can_0x152_BMS_Pack_CV_Info.DASH_Alive_Counter_152 = in;
	return 0;
}

int decode_can_0x152_BMS_Regeneration_Allowed(const can_obj_mdu_v002x_tb_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x152_BMS_Pack_CV_Info.BMS_Regeneration_Allowed);
	*out = rval;
	return 0;
}

int encode_can_0x152_BMS_Regeneration_Allowed(can_obj_mdu_v002x_tb_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x152_BMS_Pack_CV_Info.BMS_Regeneration_Allowed = in;
	return 0;
}

int decode_can_0x152_BMS_Status_FET(const can_obj_mdu_v002x_tb_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x152_BMS_Pack_CV_Info.BMS_Status_FET);
	*out = rval;
	return 0;
}

int encode_can_0x152_BMS_Status_FET(can_obj_mdu_v002x_tb_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x152_BMS_Pack_CV_Info.BMS_Status_FET = in;
	return 0;
}

int print_can_0x152_BMS_Pack_CV_Info(const can_obj_mdu_v002x_tb_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "BMS_Current_Pack = (wire: %.0f)\n", (double)(o->can_0x152_BMS_Pack_CV_Info.BMS_Current_Pack)));
	r = print_helper(r, fprintf(output, "BMS_Voltage_Pack = (wire: %.0f)\n", (double)(o->can_0x152_BMS_Pack_CV_Info.BMS_Voltage_Pack)));
	r = print_helper(r, fprintf(output, "DASH_CRC_152 = (wire: %.0f)\n", (double)(o->can_0x152_BMS_Pack_CV_Info.DASH_CRC_152)));
	r = print_helper(r, fprintf(output, "DASH_Alive_Counter_152 = (wire: %.0f)\n", (double)(o->can_0x152_BMS_Pack_CV_Info.DASH_Alive_Counter_152)));
	r = print_helper(r, fprintf(output, "BMS_Regeneration_Allowed = (wire: %.0f)\n", (double)(o->can_0x152_BMS_Pack_CV_Info.BMS_Regeneration_Allowed)));
	r = print_helper(r, fprintf(output, "BMS_Status_FET = (wire: %.0f)\n", (double)(o->can_0x152_BMS_Pack_CV_Info.BMS_Status_FET)));
	return r;
}

static int pack_can_0x260_MDU_Status_Info_2(can_obj_mdu_v002x_tb_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t m = 0;
	/* MDU_Engine_Temp: start-bit 7, length 9, endianess motorola, scaling 0.5, offset 98 */
	x = ((uint16_t)(o->can_0x260_MDU_Status_Info_2.MDU_Engine_Temp)) & 0x1ff;
	x <<= 55; 
	m |= x;
	/* MDU_Temp: start-bit 23, length 8, endianess motorola, scaling 0.5, offset 34 */
	x = ((uint8_t)(o->can_0x260_MDU_Status_Info_2.MDU_Temp)) & 0xff;
	x <<= 40; 
	m |= x;
	/* MDU_CRC_260: start-bit 60, length 5, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x260_MDU_Status_Info_2.MDU_CRC_260)) & 0x1f;
	m |= x;
	/* MDU_State: start-bit 31, length 3, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x260_MDU_Status_Info_2.MDU_State)) & 0x7;
	x <<= 37; 
	m |= x;
	/* MDU_Alive_Counter_260: start-bit 63, length 3, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x260_MDU_Status_Info_2.MDU_Alive_Counter_260)) & 0x7;
	x <<= 5; 
	m |= x;
	/* MDU_Engine_Direction_Resp: start-bit 25, length 2, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x260_MDU_Status_Info_2.MDU_Engine_Direction_Resp)) & 0x3;
	x <<= 32; 
	m |= x;
	/* MDU_Malfunction_Indica_LED: start-bit 8, length 1, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x260_MDU_Status_Info_2.MDU_Malfunction_Indica_LED)) & 0x1;
	x <<= 48; 
	m |= x;
	/* MDU_General_Failure_LED: start-bit 9, length 1, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x260_MDU_Status_Info_2.MDU_General_Failure_LED)) & 0x1;
	x <<= 49; 
	m |= x;
	/* MDU_Failure: start-bit 10, length 1, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x260_MDU_Status_Info_2.MDU_Failure)) & 0x1;
	x <<= 50; 
	m |= x;
	/* MDU_Overspeed_Warning: start-bit 11, length 1, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x260_MDU_Status_Info_2.MDU_Overspeed_Warning)) & 0x1;
	x <<= 51; 
	m |= x;
	/* MDU_Warning: start-bit 12, length 1, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x260_MDU_Status_Info_2.MDU_Warning)) & 0x1;
	x <<= 52; 
	m |= x;
	/* MDU_Temp_Warning: start-bit 13, length 1, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x260_MDU_Status_Info_2.MDU_Temp_Warning)) & 0x1;
	x <<= 53; 
	m |= x;
	/* MDU_Engine_Temp_Warning: start-bit 14, length 1, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x260_MDU_Status_Info_2.MDU_Engine_Temp_Warning)) & 0x1;
	x <<= 54; 
	m |= x;
	*data = reverse_byte_order(m);
	o->can_0x260_MDU_Status_Info_2_tx = 1;
	return 8;
}

static int unpack_can_0x260_MDU_Status_Info_2(can_obj_mdu_v002x_tb_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t m = reverse_byte_order(data);
	if (dlc < 8)
		return -1;
	/* MDU_Engine_Temp: start-bit 7, length 9, endianess motorola, scaling 0.5, offset 98 */
	x = (m >> 55) & 0x1ff;
	x = (x & 0x100) ? (x | 0xfe00) : x; 
	o->can_0x260_MDU_Status_Info_2.MDU_Engine_Temp = x;
	/* MDU_Temp: start-bit 23, length 8, endianess motorola, scaling 0.5, offset 34 */
	x = (m >> 40) & 0xff;
	o->can_0x260_MDU_Status_Info_2.MDU_Temp = x;
	/* MDU_CRC_260: start-bit 60, length 5, endianess motorola, scaling 1, offset 0 */
	x = m & 0x1f;
	o->can_0x260_MDU_Status_Info_2.MDU_CRC_260 = x;
	/* MDU_State: start-bit 31, length 3, endianess motorola, scaling 1, offset 0 */
	x = (m >> 37) & 0x7;
	o->can_0x260_MDU_Status_Info_2.MDU_State = x;
	/* MDU_Alive_Counter_260: start-bit 63, length 3, endianess motorola, scaling 1, offset 0 */
	x = (m >> 5) & 0x7;
	o->can_0x260_MDU_Status_Info_2.MDU_Alive_Counter_260 = x;
	/* MDU_Engine_Direction_Resp: start-bit 25, length 2, endianess motorola, scaling 1, offset 0 */
	x = (m >> 32) & 0x3;
	o->can_0x260_MDU_Status_Info_2.MDU_Engine_Direction_Resp = x;
	/* MDU_Malfunction_Indica_LED: start-bit 8, length 1, endianess motorola, scaling 1, offset 0 */
	x = (m >> 48) & 0x1;
	o->can_0x260_MDU_Status_Info_2.MDU_Malfunction_Indica_LED = x;
	/* MDU_General_Failure_LED: start-bit 9, length 1, endianess motorola, scaling 1, offset 0 */
	x = (m >> 49) & 0x1;
	o->can_0x260_MDU_Status_Info_2.MDU_General_Failure_LED = x;
	/* MDU_Failure: start-bit 10, length 1, endianess motorola, scaling 1, offset 0 */
	x = (m >> 50) & 0x1;
	o->can_0x260_MDU_Status_Info_2.MDU_Failure = x;
	/* MDU_Overspeed_Warning: start-bit 11, length 1, endianess motorola, scaling 1, offset 0 */
	x = (m >> 51) & 0x1;
	o->can_0x260_MDU_Status_Info_2.MDU_Overspeed_Warning = x;
	/* MDU_Warning: start-bit 12, length 1, endianess motorola, scaling 1, offset 0 */
	x = (m >> 52) & 0x1;
	o->can_0x260_MDU_Status_Info_2.MDU_Warning = x;
	/* MDU_Temp_Warning: start-bit 13, length 1, endianess motorola, scaling 1, offset 0 */
	x = (m >> 53) & 0x1;
	o->can_0x260_MDU_Status_Info_2.MDU_Temp_Warning = x;
	/* MDU_Engine_Temp_Warning: start-bit 14, length 1, endianess motorola, scaling 1, offset 0 */
	x = (m >> 54) & 0x1;
	o->can_0x260_MDU_Status_Info_2.MDU_Engine_Temp_Warning = x;
	o->can_0x260_MDU_Status_Info_2_rx = 1;
	o->can_0x260_MDU_Status_Info_2_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x260_MDU_Engine_Temp(const can_obj_mdu_v002x_tb_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x260_MDU_Status_Info_2.MDU_Engine_Temp);
	rval *= 0.5;
	rval += 98;
	if ((rval >= -30) && (rval <= 225.5)) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x260_MDU_Engine_Temp(can_obj_mdu_v002x_tb_h_t *o, double in) {
	assert(o);
	o->can_0x260_MDU_Status_Info_2.MDU_Engine_Temp = 0;
	if (in < -30)
		return -1;
	if (in > 225.5)
		return -1;
	in += -98;
	in *= 2;
	o->can_0x260_MDU_Status_Info_2.MDU_Engine_Temp = in;
	return 0;
}

int decode_can_0x260_MDU_Temp(const can_obj_mdu_v002x_tb_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x260_MDU_Status_Info_2.MDU_Temp);
	rval *= 0.5;
	rval += 34;
	if ((rval >= -30) && (rval <= 97.5)) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x260_MDU_Temp(can_obj_mdu_v002x_tb_h_t *o, double in) {
	assert(o);
	o->can_0x260_MDU_Status_Info_2.MDU_Temp = 0;
	if (in < -30)
		return -1;
	if (in > 97.5)
		return -1;
	in += -34;
	in *= 2;
	o->can_0x260_MDU_Status_Info_2.MDU_Temp = in;
	return 0;
}

int decode_can_0x260_MDU_CRC_260(const can_obj_mdu_v002x_tb_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x260_MDU_Status_Info_2.MDU_CRC_260);
	*out = rval;
	return 0;
}

int encode_can_0x260_MDU_CRC_260(can_obj_mdu_v002x_tb_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x260_MDU_Status_Info_2.MDU_CRC_260 = in;
	return 0;
}

int decode_can_0x260_MDU_State(const can_obj_mdu_v002x_tb_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x260_MDU_Status_Info_2.MDU_State);
	*out = rval;
	return 0;
}

int encode_can_0x260_MDU_State(can_obj_mdu_v002x_tb_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x260_MDU_Status_Info_2.MDU_State = in;
	return 0;
}

int decode_can_0x260_MDU_Alive_Counter_260(const can_obj_mdu_v002x_tb_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x260_MDU_Status_Info_2.MDU_Alive_Counter_260);
	if (rval <= 6) {
		*out = rval;
		return 0;
	} else {
		*out = (uint8_t)0;
		return -1;
	}
}

int encode_can_0x260_MDU_Alive_Counter_260(can_obj_mdu_v002x_tb_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x260_MDU_Status_Info_2.MDU_Alive_Counter_260 = 0;
	if (in > 6)
		return -1;
	o->can_0x260_MDU_Status_Info_2.MDU_Alive_Counter_260 = in;
	return 0;
}

int decode_can_0x260_MDU_Engine_Direction_Resp(const can_obj_mdu_v002x_tb_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x260_MDU_Status_Info_2.MDU_Engine_Direction_Resp);
	*out = rval;
	return 0;
}

int encode_can_0x260_MDU_Engine_Direction_Resp(can_obj_mdu_v002x_tb_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x260_MDU_Status_Info_2.MDU_Engine_Direction_Resp = in;
	return 0;
}

int decode_can_0x260_MDU_Malfunction_Indica_LED(const can_obj_mdu_v002x_tb_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x260_MDU_Status_Info_2.MDU_Malfunction_Indica_LED);
	*out = rval;
	return 0;
}

int encode_can_0x260_MDU_Malfunction_Indica_LED(can_obj_mdu_v002x_tb_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x260_MDU_Status_Info_2.MDU_Malfunction_Indica_LED = in;
	return 0;
}

int decode_can_0x260_MDU_General_Failure_LED(const can_obj_mdu_v002x_tb_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x260_MDU_Status_Info_2.MDU_General_Failure_LED);
	*out = rval;
	return 0;
}

int encode_can_0x260_MDU_General_Failure_LED(can_obj_mdu_v002x_tb_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x260_MDU_Status_Info_2.MDU_General_Failure_LED = in;
	return 0;
}

int decode_can_0x260_MDU_Failure(const can_obj_mdu_v002x_tb_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x260_MDU_Status_Info_2.MDU_Failure);
	*out = rval;
	return 0;
}

int encode_can_0x260_MDU_Failure(can_obj_mdu_v002x_tb_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x260_MDU_Status_Info_2.MDU_Failure = in;
	return 0;
}

int decode_can_0x260_MDU_Overspeed_Warning(const can_obj_mdu_v002x_tb_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x260_MDU_Status_Info_2.MDU_Overspeed_Warning);
	*out = rval;
	return 0;
}

int encode_can_0x260_MDU_Overspeed_Warning(can_obj_mdu_v002x_tb_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x260_MDU_Status_Info_2.MDU_Overspeed_Warning = in;
	return 0;
}

int decode_can_0x260_MDU_Warning(const can_obj_mdu_v002x_tb_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x260_MDU_Status_Info_2.MDU_Warning);
	*out = rval;
	return 0;
}

int encode_can_0x260_MDU_Warning(can_obj_mdu_v002x_tb_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x260_MDU_Status_Info_2.MDU_Warning = in;
	return 0;
}

int decode_can_0x260_MDU_Temp_Warning(const can_obj_mdu_v002x_tb_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x260_MDU_Status_Info_2.MDU_Temp_Warning);
	*out = rval;
	return 0;
}

int encode_can_0x260_MDU_Temp_Warning(can_obj_mdu_v002x_tb_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x260_MDU_Status_Info_2.MDU_Temp_Warning = in;
	return 0;
}

int decode_can_0x260_MDU_Engine_Temp_Warning(const can_obj_mdu_v002x_tb_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x260_MDU_Status_Info_2.MDU_Engine_Temp_Warning);
	*out = rval;
	return 0;
}

int encode_can_0x260_MDU_Engine_Temp_Warning(can_obj_mdu_v002x_tb_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x260_MDU_Status_Info_2.MDU_Engine_Temp_Warning = in;
	return 0;
}

int print_can_0x260_MDU_Status_Info_2(const can_obj_mdu_v002x_tb_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "MDU_Engine_Temp = (wire: %.0f)\n", (double)(o->can_0x260_MDU_Status_Info_2.MDU_Engine_Temp)));
	r = print_helper(r, fprintf(output, "MDU_Temp = (wire: %.0f)\n", (double)(o->can_0x260_MDU_Status_Info_2.MDU_Temp)));
	r = print_helper(r, fprintf(output, "MDU_CRC_260 = (wire: %.0f)\n", (double)(o->can_0x260_MDU_Status_Info_2.MDU_CRC_260)));
	r = print_helper(r, fprintf(output, "MDU_State = (wire: %.0f)\n", (double)(o->can_0x260_MDU_Status_Info_2.MDU_State)));
	r = print_helper(r, fprintf(output, "MDU_Alive_Counter_260 = (wire: %.0f)\n", (double)(o->can_0x260_MDU_Status_Info_2.MDU_Alive_Counter_260)));
	r = print_helper(r, fprintf(output, "MDU_Engine_Direction_Resp = (wire: %.0f)\n", (double)(o->can_0x260_MDU_Status_Info_2.MDU_Engine_Direction_Resp)));
	r = print_helper(r, fprintf(output, "MDU_Malfunction_Indica_LED = (wire: %.0f)\n", (double)(o->can_0x260_MDU_Status_Info_2.MDU_Malfunction_Indica_LED)));
	r = print_helper(r, fprintf(output, "MDU_General_Failure_LED = (wire: %.0f)\n", (double)(o->can_0x260_MDU_Status_Info_2.MDU_General_Failure_LED)));
	r = print_helper(r, fprintf(output, "MDU_Failure = (wire: %.0f)\n", (double)(o->can_0x260_MDU_Status_Info_2.MDU_Failure)));
	r = print_helper(r, fprintf(output, "MDU_Overspeed_Warning = (wire: %.0f)\n", (double)(o->can_0x260_MDU_Status_Info_2.MDU_Overspeed_Warning)));
	r = print_helper(r, fprintf(output, "MDU_Warning = (wire: %.0f)\n", (double)(o->can_0x260_MDU_Status_Info_2.MDU_Warning)));
	r = print_helper(r, fprintf(output, "MDU_Temp_Warning = (wire: %.0f)\n", (double)(o->can_0x260_MDU_Status_Info_2.MDU_Temp_Warning)));
	r = print_helper(r, fprintf(output, "MDU_Engine_Temp_Warning = (wire: %.0f)\n", (double)(o->can_0x260_MDU_Status_Info_2.MDU_Engine_Temp_Warning)));
	return r;
}

static int pack_can_0x55a_DASH_Bike_Info(can_obj_mdu_v002x_tb_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t m = 0;
	/* DASH_Odo_Meter_Extended: start-bit 7, length 24, endianess motorola, scaling 0.1, offset 0 */
	x = ((uint32_t)(o->can_0x55a_DASH_Bike_Info.DASH_Odo_Meter_Extended)) & 0xffffff;
	x <<= 40; 
	m |= x;
	*data = reverse_byte_order(m);
	o->can_0x55a_DASH_Bike_Info_tx = 1;
	return 8;
}

static int unpack_can_0x55a_DASH_Bike_Info(can_obj_mdu_v002x_tb_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t m = reverse_byte_order(data);
	if (dlc < 8)
		return -1;
	/* DASH_Odo_Meter_Extended: start-bit 7, length 24, endianess motorola, scaling 0.1, offset 0 */
	x = (m >> 40) & 0xffffff;
	o->can_0x55a_DASH_Bike_Info.DASH_Odo_Meter_Extended = x;
	o->can_0x55a_DASH_Bike_Info_rx = 1;
	o->can_0x55a_DASH_Bike_Info_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x55a_DASH_Odo_Meter_Extended(const can_obj_mdu_v002x_tb_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x55a_DASH_Bike_Info.DASH_Odo_Meter_Extended);
	rval *= 0.1;
	if (rval <= 1e+06) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x55a_DASH_Odo_Meter_Extended(can_obj_mdu_v002x_tb_h_t *o, double in) {
	assert(o);
	o->can_0x55a_DASH_Bike_Info.DASH_Odo_Meter_Extended = 0;
	if (in > 1e+06)
		return -1;
	in *= 10;
	o->can_0x55a_DASH_Bike_Info.DASH_Odo_Meter_Extended = in;
	return 0;
}

int print_can_0x55a_DASH_Bike_Info(const can_obj_mdu_v002x_tb_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "DASH_Odo_Meter_Extended = (wire: %.0f)\n", (double)(o->can_0x55a_DASH_Bike_Info.DASH_Odo_Meter_Extended)));
	return r;
}

static int pack_can_0x580_VCU_Vehicle_Info(can_obj_mdu_v002x_tb_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t m = 0;
	/* VCU_Hourmeter: start-bit 7, length 16, endianess motorola, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x580_VCU_Vehicle_Info.VCU_Hourmeter)) & 0xffff;
	x <<= 48; 
	m |= x;
	/* VCU_Est_Range: start-bit 23, length 8, endianess motorola, scaling 5, offset 0 */
	x = ((uint8_t)(o->can_0x580_VCU_Vehicle_Info.VCU_Est_Range)) & 0xff;
	x <<= 40; 
	m |= x;
	/* VCU_Est_Riding_Time: start-bit 39, length 8, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x580_VCU_Vehicle_Info.VCU_Est_Riding_Time)) & 0xff;
	x <<= 24; 
	m |= x;
	/* VCU_Drivecycle_Detected: start-bit 31, length 1, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x580_VCU_Vehicle_Info.VCU_Drivecycle_Detected)) & 0x1;
	x <<= 39; 
	m |= x;
	*data = reverse_byte_order(m);
	o->can_0x580_VCU_Vehicle_Info_tx = 1;
	return 8;
}

static int unpack_can_0x580_VCU_Vehicle_Info(can_obj_mdu_v002x_tb_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t m = reverse_byte_order(data);
	if (dlc < 8)
		return -1;
	/* VCU_Hourmeter: start-bit 7, length 16, endianess motorola, scaling 0.1, offset 0 */
	x = (m >> 48) & 0xffff;
	o->can_0x580_VCU_Vehicle_Info.VCU_Hourmeter = x;
	/* VCU_Est_Range: start-bit 23, length 8, endianess motorola, scaling 5, offset 0 */
	x = (m >> 40) & 0xff;
	o->can_0x580_VCU_Vehicle_Info.VCU_Est_Range = x;
	/* VCU_Est_Riding_Time: start-bit 39, length 8, endianess motorola, scaling 1, offset 0 */
	x = (m >> 24) & 0xff;
	o->can_0x580_VCU_Vehicle_Info.VCU_Est_Riding_Time = x;
	/* VCU_Drivecycle_Detected: start-bit 31, length 1, endianess motorola, scaling 1, offset 0 */
	x = (m >> 39) & 0x1;
	o->can_0x580_VCU_Vehicle_Info.VCU_Drivecycle_Detected = x;
	o->can_0x580_VCU_Vehicle_Info_rx = 1;
	o->can_0x580_VCU_Vehicle_Info_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x580_VCU_Hourmeter(const can_obj_mdu_v002x_tb_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x580_VCU_Vehicle_Info.VCU_Hourmeter);
	rval *= 0.1;
	if (rval <= 6535.5) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x580_VCU_Hourmeter(can_obj_mdu_v002x_tb_h_t *o, double in) {
	assert(o);
	o->can_0x580_VCU_Vehicle_Info.VCU_Hourmeter = 0;
	if (in > 6535.5)
		return -1;
	in *= 10;
	o->can_0x580_VCU_Vehicle_Info.VCU_Hourmeter = in;
	return 0;
}

int decode_can_0x580_VCU_Est_Range(const can_obj_mdu_v002x_tb_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x580_VCU_Vehicle_Info.VCU_Est_Range);
	rval *= 5;
	*out = rval;
	return 0;
}

int encode_can_0x580_VCU_Est_Range(can_obj_mdu_v002x_tb_h_t *o, double in) {
	assert(o);
	in *= 0.2;
	o->can_0x580_VCU_Vehicle_Info.VCU_Est_Range = in;
	return 0;
}

int decode_can_0x580_VCU_Est_Riding_Time(const can_obj_mdu_v002x_tb_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x580_VCU_Vehicle_Info.VCU_Est_Riding_Time);
	*out = rval;
	return 0;
}

int encode_can_0x580_VCU_Est_Riding_Time(can_obj_mdu_v002x_tb_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x580_VCU_Vehicle_Info.VCU_Est_Riding_Time = in;
	return 0;
}

int decode_can_0x580_VCU_Drivecycle_Detected(const can_obj_mdu_v002x_tb_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x580_VCU_Vehicle_Info.VCU_Drivecycle_Detected);
	*out = rval;
	return 0;
}

int encode_can_0x580_VCU_Drivecycle_Detected(can_obj_mdu_v002x_tb_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x580_VCU_Vehicle_Info.VCU_Drivecycle_Detected = in;
	return 0;
}

int print_can_0x580_VCU_Vehicle_Info(const can_obj_mdu_v002x_tb_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "VCU_Hourmeter = (wire: %.0f)\n", (double)(o->can_0x580_VCU_Vehicle_Info.VCU_Hourmeter)));
	r = print_helper(r, fprintf(output, "VCU_Est_Range = (wire: %.0f)\n", (double)(o->can_0x580_VCU_Vehicle_Info.VCU_Est_Range)));
	r = print_helper(r, fprintf(output, "VCU_Est_Riding_Time = (wire: %.0f)\n", (double)(o->can_0x580_VCU_Vehicle_Info.VCU_Est_Riding_Time)));
	r = print_helper(r, fprintf(output, "VCU_Drivecycle_Detected = (wire: %.0f)\n", (double)(o->can_0x580_VCU_Vehicle_Info.VCU_Drivecycle_Detected)));
	return r;
}

static int pack_can_0x734_MDU_Debug_1(can_obj_mdu_v002x_tb_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t m = 0;
	/* MDU_Limited_Torq_Req: start-bit 7, length 16, endianess motorola, scaling 0.05, offset 0 */
	x = ((uint16_t)(o->can_0x734_MDU_Debug_1.MDU_Limited_Torq_Req)) & 0xffff;
	x <<= 48; 
	m |= x;
	/* MDU_Phase_A_volt: start-bit 23, length 16, endianess motorola, scaling 0.02, offset 0 */
	x = ((uint16_t)(o->can_0x734_MDU_Debug_1.MDU_Phase_A_volt)) & 0xffff;
	x <<= 32; 
	m |= x;
	/* MDU_Phase_B_volt: start-bit 39, length 16, endianess motorola, scaling 0.02, offset 0 */
	x = ((uint16_t)(o->can_0x734_MDU_Debug_1.MDU_Phase_B_volt)) & 0xffff;
	x <<= 16; 
	m |= x;
	/* MDU_Received_Torq_Req: start-bit 55, length 16, endianess motorola, scaling 0.05, offset 0 */
	x = ((uint16_t)(o->can_0x734_MDU_Debug_1.MDU_Received_Torq_Req)) & 0xffff;
	m |= x;
	*data = reverse_byte_order(m);
	o->can_0x734_MDU_Debug_1_tx = 1;
	return 8;
}

static int unpack_can_0x734_MDU_Debug_1(can_obj_mdu_v002x_tb_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t m = reverse_byte_order(data);
	if (dlc < 8)
		return -1;
	/* MDU_Limited_Torq_Req: start-bit 7, length 16, endianess motorola, scaling 0.05, offset 0 */
	x = (m >> 48) & 0xffff;
	o->can_0x734_MDU_Debug_1.MDU_Limited_Torq_Req = x;
	/* MDU_Phase_A_volt: start-bit 23, length 16, endianess motorola, scaling 0.02, offset 0 */
	x = (m >> 32) & 0xffff;
	o->can_0x734_MDU_Debug_1.MDU_Phase_A_volt = x;
	/* MDU_Phase_B_volt: start-bit 39, length 16, endianess motorola, scaling 0.02, offset 0 */
	x = (m >> 16) & 0xffff;
	o->can_0x734_MDU_Debug_1.MDU_Phase_B_volt = x;
	/* MDU_Received_Torq_Req: start-bit 55, length 16, endianess motorola, scaling 0.05, offset 0 */
	x = m & 0xffff;
	o->can_0x734_MDU_Debug_1.MDU_Received_Torq_Req = x;
	o->can_0x734_MDU_Debug_1_rx = 1;
	o->can_0x734_MDU_Debug_1_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x734_MDU_Limited_Torq_Req(const can_obj_mdu_v002x_tb_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x734_MDU_Debug_1.MDU_Limited_Torq_Req);
	rval *= 0.05;
	if ((rval >= -1000) && (rval <= 1000)) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x734_MDU_Limited_Torq_Req(can_obj_mdu_v002x_tb_h_t *o, double in) {
	assert(o);
	o->can_0x734_MDU_Debug_1.MDU_Limited_Torq_Req = 0;
	if (in < -1000)
		return -1;
	if (in > 1000)
		return -1;
	in *= 20;
	o->can_0x734_MDU_Debug_1.MDU_Limited_Torq_Req = in;
	return 0;
}

int decode_can_0x734_MDU_Phase_A_volt(const can_obj_mdu_v002x_tb_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x734_MDU_Debug_1.MDU_Phase_A_volt);
	rval *= 0.02;
	if ((rval >= -655.35) && (rval <= 655.34)) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x734_MDU_Phase_A_volt(can_obj_mdu_v002x_tb_h_t *o, double in) {
	assert(o);
	o->can_0x734_MDU_Debug_1.MDU_Phase_A_volt = 0;
	if (in < -655.35)
		return -1;
	if (in > 655.34)
		return -1;
	in *= 50;
	o->can_0x734_MDU_Debug_1.MDU_Phase_A_volt = in;
	return 0;
}

int decode_can_0x734_MDU_Phase_B_volt(const can_obj_mdu_v002x_tb_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x734_MDU_Debug_1.MDU_Phase_B_volt);
	rval *= 0.02;
	if ((rval >= -655.35) && (rval <= 655.34)) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x734_MDU_Phase_B_volt(can_obj_mdu_v002x_tb_h_t *o, double in) {
	assert(o);
	o->can_0x734_MDU_Debug_1.MDU_Phase_B_volt = 0;
	if (in < -655.35)
		return -1;
	if (in > 655.34)
		return -1;
	in *= 50;
	o->can_0x734_MDU_Debug_1.MDU_Phase_B_volt = in;
	return 0;
}

int decode_can_0x734_MDU_Received_Torq_Req(const can_obj_mdu_v002x_tb_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x734_MDU_Debug_1.MDU_Received_Torq_Req);
	rval *= 0.05;
	if ((rval >= -1000) && (rval <= 1000)) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x734_MDU_Received_Torq_Req(can_obj_mdu_v002x_tb_h_t *o, double in) {
	assert(o);
	o->can_0x734_MDU_Debug_1.MDU_Received_Torq_Req = 0;
	if (in < -1000)
		return -1;
	if (in > 1000)
		return -1;
	in *= 20;
	o->can_0x734_MDU_Debug_1.MDU_Received_Torq_Req = in;
	return 0;
}

int print_can_0x734_MDU_Debug_1(const can_obj_mdu_v002x_tb_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "MDU_Limited_Torq_Req = (wire: %.0f)\n", (double)(o->can_0x734_MDU_Debug_1.MDU_Limited_Torq_Req)));
	r = print_helper(r, fprintf(output, "MDU_Phase_A_volt = (wire: %.0f)\n", (double)(o->can_0x734_MDU_Debug_1.MDU_Phase_A_volt)));
	r = print_helper(r, fprintf(output, "MDU_Phase_B_volt = (wire: %.0f)\n", (double)(o->can_0x734_MDU_Debug_1.MDU_Phase_B_volt)));
	r = print_helper(r, fprintf(output, "MDU_Received_Torq_Req = (wire: %.0f)\n", (double)(o->can_0x734_MDU_Debug_1.MDU_Received_Torq_Req)));
	return r;
}

static int pack_can_0x735_MDU_Debug_2(can_obj_mdu_v002x_tb_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t m = 0;
	/* MDU_Phase_A_amps: start-bit 7, length 16, endianess motorola, scaling 0.01, offset 0 */
	x = ((uint16_t)(o->can_0x735_MDU_Debug_2.MDU_Phase_A_amps)) & 0xffff;
	x <<= 48; 
	m |= x;
	/* MDU_Phase_B_amps: start-bit 23, length 16, endianess motorola, scaling 0.01, offset 0 */
	x = ((uint16_t)(o->can_0x735_MDU_Debug_2.MDU_Phase_B_amps)) & 0xffff;
	x <<= 32; 
	m |= x;
	/* MDU_Phase_C_amps: start-bit 39, length 16, endianess motorola, scaling 0.01, offset 0 */
	x = ((uint16_t)(o->can_0x735_MDU_Debug_2.MDU_Phase_C_amps)) & 0xffff;
	x <<= 16; 
	m |= x;
	/* MDU_Phase_C_volt: start-bit 55, length 16, endianess motorola, scaling 0.02, offset 0 */
	x = ((uint16_t)(o->can_0x735_MDU_Debug_2.MDU_Phase_C_volt)) & 0xffff;
	m |= x;
	*data = reverse_byte_order(m);
	o->can_0x735_MDU_Debug_2_tx = 1;
	return 8;
}

static int unpack_can_0x735_MDU_Debug_2(can_obj_mdu_v002x_tb_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t m = reverse_byte_order(data);
	if (dlc < 8)
		return -1;
	/* MDU_Phase_A_amps: start-bit 7, length 16, endianess motorola, scaling 0.01, offset 0 */
	x = (m >> 48) & 0xffff;
	o->can_0x735_MDU_Debug_2.MDU_Phase_A_amps = x;
	/* MDU_Phase_B_amps: start-bit 23, length 16, endianess motorola, scaling 0.01, offset 0 */
	x = (m >> 32) & 0xffff;
	o->can_0x735_MDU_Debug_2.MDU_Phase_B_amps = x;
	/* MDU_Phase_C_amps: start-bit 39, length 16, endianess motorola, scaling 0.01, offset 0 */
	x = (m >> 16) & 0xffff;
	o->can_0x735_MDU_Debug_2.MDU_Phase_C_amps = x;
	/* MDU_Phase_C_volt: start-bit 55, length 16, endianess motorola, scaling 0.02, offset 0 */
	x = m & 0xffff;
	o->can_0x735_MDU_Debug_2.MDU_Phase_C_volt = x;
	o->can_0x735_MDU_Debug_2_rx = 1;
	o->can_0x735_MDU_Debug_2_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x735_MDU_Phase_A_amps(const can_obj_mdu_v002x_tb_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x735_MDU_Debug_2.MDU_Phase_A_amps);
	rval *= 0.01;
	if ((rval >= -250) && (rval <= 250)) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x735_MDU_Phase_A_amps(can_obj_mdu_v002x_tb_h_t *o, double in) {
	assert(o);
	o->can_0x735_MDU_Debug_2.MDU_Phase_A_amps = 0;
	if (in < -250)
		return -1;
	if (in > 250)
		return -1;
	in *= 100;
	o->can_0x735_MDU_Debug_2.MDU_Phase_A_amps = in;
	return 0;
}

int decode_can_0x735_MDU_Phase_B_amps(const can_obj_mdu_v002x_tb_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x735_MDU_Debug_2.MDU_Phase_B_amps);
	rval *= 0.01;
	if ((rval >= -250) && (rval <= 250)) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x735_MDU_Phase_B_amps(can_obj_mdu_v002x_tb_h_t *o, double in) {
	assert(o);
	o->can_0x735_MDU_Debug_2.MDU_Phase_B_amps = 0;
	if (in < -250)
		return -1;
	if (in > 250)
		return -1;
	in *= 100;
	o->can_0x735_MDU_Debug_2.MDU_Phase_B_amps = in;
	return 0;
}

int decode_can_0x735_MDU_Phase_C_amps(const can_obj_mdu_v002x_tb_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x735_MDU_Debug_2.MDU_Phase_C_amps);
	rval *= 0.01;
	if ((rval >= -250) && (rval <= 250)) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x735_MDU_Phase_C_amps(can_obj_mdu_v002x_tb_h_t *o, double in) {
	assert(o);
	o->can_0x735_MDU_Debug_2.MDU_Phase_C_amps = 0;
	if (in < -250)
		return -1;
	if (in > 250)
		return -1;
	in *= 100;
	o->can_0x735_MDU_Debug_2.MDU_Phase_C_amps = in;
	return 0;
}

int decode_can_0x735_MDU_Phase_C_volt(const can_obj_mdu_v002x_tb_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x735_MDU_Debug_2.MDU_Phase_C_volt);
	rval *= 0.02;
	if ((rval >= -655.35) && (rval <= 655.34)) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x735_MDU_Phase_C_volt(can_obj_mdu_v002x_tb_h_t *o, double in) {
	assert(o);
	o->can_0x735_MDU_Debug_2.MDU_Phase_C_volt = 0;
	if (in < -655.35)
		return -1;
	if (in > 655.34)
		return -1;
	in *= 50;
	o->can_0x735_MDU_Debug_2.MDU_Phase_C_volt = in;
	return 0;
}

int print_can_0x735_MDU_Debug_2(const can_obj_mdu_v002x_tb_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "MDU_Phase_A_amps = (wire: %.0f)\n", (double)(o->can_0x735_MDU_Debug_2.MDU_Phase_A_amps)));
	r = print_helper(r, fprintf(output, "MDU_Phase_B_amps = (wire: %.0f)\n", (double)(o->can_0x735_MDU_Debug_2.MDU_Phase_B_amps)));
	r = print_helper(r, fprintf(output, "MDU_Phase_C_amps = (wire: %.0f)\n", (double)(o->can_0x735_MDU_Debug_2.MDU_Phase_C_amps)));
	r = print_helper(r, fprintf(output, "MDU_Phase_C_volt = (wire: %.0f)\n", (double)(o->can_0x735_MDU_Debug_2.MDU_Phase_C_volt)));
	return r;
}

static int pack_can_0x736_MDU_Debug_3(can_obj_mdu_v002x_tb_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t m = 0;
	/* MDU_DC_Bus_amps_calc: start-bit 23, length 16, endianess motorola, scaling 0.01, offset 0 */
	x = ((uint16_t)(o->can_0x736_MDU_Debug_3.MDU_DC_Bus_amps_calc)) & 0xffff;
	x <<= 32; 
	m |= x;
	/* MDU_Iq_measured: start-bit 39, length 16, endianess motorola, scaling 0.01, offset 0 */
	x = ((uint16_t)(o->can_0x736_MDU_Debug_3.MDU_Iq_measured)) & 0xffff;
	x <<= 16; 
	m |= x;
	/* MDU_Iq_request: start-bit 55, length 16, endianess motorola, scaling 0.01, offset 0 */
	x = ((uint16_t)(o->can_0x736_MDU_Debug_3.MDU_Iq_request)) & 0xffff;
	m |= x;
	/* MDU_DC_Bus_volt: start-bit 6, length 15, endianess motorola, scaling 0.02, offset 0 */
	x = ((uint16_t)(o->can_0x736_MDU_Debug_3.MDU_DC_Bus_volt)) & 0x7fff;
	x <<= 48; 
	m |= x;
	/* MDU_gate_ready: start-bit 7, length 1, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x736_MDU_Debug_3.MDU_gate_ready)) & 0x1;
	x <<= 63; 
	m |= x;
	*data = reverse_byte_order(m);
	o->can_0x736_MDU_Debug_3_tx = 1;
	return 8;
}

static int unpack_can_0x736_MDU_Debug_3(can_obj_mdu_v002x_tb_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t m = reverse_byte_order(data);
	if (dlc < 8)
		return -1;
	/* MDU_DC_Bus_amps_calc: start-bit 23, length 16, endianess motorola, scaling 0.01, offset 0 */
	x = (m >> 32) & 0xffff;
	o->can_0x736_MDU_Debug_3.MDU_DC_Bus_amps_calc = x;
	/* MDU_Iq_measured: start-bit 39, length 16, endianess motorola, scaling 0.01, offset 0 */
	x = (m >> 16) & 0xffff;
	o->can_0x736_MDU_Debug_3.MDU_Iq_measured = x;
	/* MDU_Iq_request: start-bit 55, length 16, endianess motorola, scaling 0.01, offset 0 */
	x = m & 0xffff;
	o->can_0x736_MDU_Debug_3.MDU_Iq_request = x;
	/* MDU_DC_Bus_volt: start-bit 6, length 15, endianess motorola, scaling 0.02, offset 0 */
	x = (m >> 48) & 0x7fff;
	o->can_0x736_MDU_Debug_3.MDU_DC_Bus_volt = x;
	/* MDU_gate_ready: start-bit 7, length 1, endianess motorola, scaling 1, offset 0 */
	x = (m >> 63) & 0x1;
	o->can_0x736_MDU_Debug_3.MDU_gate_ready = x;
	o->can_0x736_MDU_Debug_3_rx = 1;
	o->can_0x736_MDU_Debug_3_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x736_MDU_DC_Bus_amps_calc(const can_obj_mdu_v002x_tb_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x736_MDU_Debug_3.MDU_DC_Bus_amps_calc);
	rval *= 0.01;
	if ((rval >= -250) && (rval <= 250)) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x736_MDU_DC_Bus_amps_calc(can_obj_mdu_v002x_tb_h_t *o, double in) {
	assert(o);
	o->can_0x736_MDU_Debug_3.MDU_DC_Bus_amps_calc = 0;
	if (in < -250)
		return -1;
	if (in > 250)
		return -1;
	in *= 100;
	o->can_0x736_MDU_Debug_3.MDU_DC_Bus_amps_calc = in;
	return 0;
}

int decode_can_0x736_MDU_Iq_measured(const can_obj_mdu_v002x_tb_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x736_MDU_Debug_3.MDU_Iq_measured);
	rval *= 0.01;
	if ((rval >= -250) && (rval <= 250)) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x736_MDU_Iq_measured(can_obj_mdu_v002x_tb_h_t *o, double in) {
	assert(o);
	o->can_0x736_MDU_Debug_3.MDU_Iq_measured = 0;
	if (in < -250)
		return -1;
	if (in > 250)
		return -1;
	in *= 100;
	o->can_0x736_MDU_Debug_3.MDU_Iq_measured = in;
	return 0;
}

int decode_can_0x736_MDU_Iq_request(const can_obj_mdu_v002x_tb_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x736_MDU_Debug_3.MDU_Iq_request);
	rval *= 0.01;
	if ((rval >= -250) && (rval <= 250)) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x736_MDU_Iq_request(can_obj_mdu_v002x_tb_h_t *o, double in) {
	assert(o);
	o->can_0x736_MDU_Debug_3.MDU_Iq_request = 0;
	if (in < -250)
		return -1;
	if (in > 250)
		return -1;
	in *= 100;
	o->can_0x736_MDU_Debug_3.MDU_Iq_request = in;
	return 0;
}

int decode_can_0x736_MDU_DC_Bus_volt(const can_obj_mdu_v002x_tb_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x736_MDU_Debug_3.MDU_DC_Bus_volt);
	rval *= 0.02;
	if (rval <= 655.35) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x736_MDU_DC_Bus_volt(can_obj_mdu_v002x_tb_h_t *o, double in) {
	assert(o);
	o->can_0x736_MDU_Debug_3.MDU_DC_Bus_volt = 0;
	if (in > 655.35)
		return -1;
	in *= 50;
	o->can_0x736_MDU_Debug_3.MDU_DC_Bus_volt = in;
	return 0;
}

int decode_can_0x736_MDU_gate_ready(const can_obj_mdu_v002x_tb_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x736_MDU_Debug_3.MDU_gate_ready);
	*out = rval;
	return 0;
}

int encode_can_0x736_MDU_gate_ready(can_obj_mdu_v002x_tb_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x736_MDU_Debug_3.MDU_gate_ready = in;
	return 0;
}

int print_can_0x736_MDU_Debug_3(const can_obj_mdu_v002x_tb_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "MDU_DC_Bus_amps_calc = (wire: %.0f)\n", (double)(o->can_0x736_MDU_Debug_3.MDU_DC_Bus_amps_calc)));
	r = print_helper(r, fprintf(output, "MDU_Iq_measured = (wire: %.0f)\n", (double)(o->can_0x736_MDU_Debug_3.MDU_Iq_measured)));
	r = print_helper(r, fprintf(output, "MDU_Iq_request = (wire: %.0f)\n", (double)(o->can_0x736_MDU_Debug_3.MDU_Iq_request)));
	r = print_helper(r, fprintf(output, "MDU_DC_Bus_volt = (wire: %.0f)\n", (double)(o->can_0x736_MDU_Debug_3.MDU_DC_Bus_volt)));
	r = print_helper(r, fprintf(output, "MDU_gate_ready = (wire: %.0f)\n", (double)(o->can_0x736_MDU_Debug_3.MDU_gate_ready)));
	return r;
}

static int pack_can_0x737_MDU_Debug_4(can_obj_mdu_v002x_tb_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t m = 0;
	/* MDU_Id_measured: start-bit 7, length 16, endianess motorola, scaling 0.01, offset 0 */
	x = ((uint16_t)(o->can_0x737_MDU_Debug_4.MDU_Id_measured)) & 0xffff;
	x <<= 48; 
	m |= x;
	/* MDU_Id_request: start-bit 23, length 16, endianess motorola, scaling 0.01, offset 0 */
	x = ((uint16_t)(o->can_0x737_MDU_Debug_4.MDU_Id_request)) & 0xffff;
	x <<= 32; 
	m |= x;
	/* MDU_uq_measured: start-bit 39, length 16, endianess motorola, scaling 0.02, offset 0 */
	x = ((uint16_t)(o->can_0x737_MDU_Debug_4.MDU_uq_measured)) & 0xffff;
	x <<= 16; 
	m |= x;
	/* MDU_uq_request: start-bit 55, length 16, endianess motorola, scaling 0.02, offset 0 */
	x = ((uint16_t)(o->can_0x737_MDU_Debug_4.MDU_uq_request)) & 0xffff;
	m |= x;
	*data = reverse_byte_order(m);
	o->can_0x737_MDU_Debug_4_tx = 1;
	return 8;
}

static int unpack_can_0x737_MDU_Debug_4(can_obj_mdu_v002x_tb_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t m = reverse_byte_order(data);
	if (dlc < 8)
		return -1;
	/* MDU_Id_measured: start-bit 7, length 16, endianess motorola, scaling 0.01, offset 0 */
	x = (m >> 48) & 0xffff;
	o->can_0x737_MDU_Debug_4.MDU_Id_measured = x;
	/* MDU_Id_request: start-bit 23, length 16, endianess motorola, scaling 0.01, offset 0 */
	x = (m >> 32) & 0xffff;
	o->can_0x737_MDU_Debug_4.MDU_Id_request = x;
	/* MDU_uq_measured: start-bit 39, length 16, endianess motorola, scaling 0.02, offset 0 */
	x = (m >> 16) & 0xffff;
	o->can_0x737_MDU_Debug_4.MDU_uq_measured = x;
	/* MDU_uq_request: start-bit 55, length 16, endianess motorola, scaling 0.02, offset 0 */
	x = m & 0xffff;
	o->can_0x737_MDU_Debug_4.MDU_uq_request = x;
	o->can_0x737_MDU_Debug_4_rx = 1;
	o->can_0x737_MDU_Debug_4_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x737_MDU_Id_measured(const can_obj_mdu_v002x_tb_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x737_MDU_Debug_4.MDU_Id_measured);
	rval *= 0.01;
	if ((rval >= -250) && (rval <= 250)) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x737_MDU_Id_measured(can_obj_mdu_v002x_tb_h_t *o, double in) {
	assert(o);
	o->can_0x737_MDU_Debug_4.MDU_Id_measured = 0;
	if (in < -250)
		return -1;
	if (in > 250)
		return -1;
	in *= 100;
	o->can_0x737_MDU_Debug_4.MDU_Id_measured = in;
	return 0;
}

int decode_can_0x737_MDU_Id_request(const can_obj_mdu_v002x_tb_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x737_MDU_Debug_4.MDU_Id_request);
	rval *= 0.01;
	if ((rval >= -250) && (rval <= 250)) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x737_MDU_Id_request(can_obj_mdu_v002x_tb_h_t *o, double in) {
	assert(o);
	o->can_0x737_MDU_Debug_4.MDU_Id_request = 0;
	if (in < -250)
		return -1;
	if (in > 250)
		return -1;
	in *= 100;
	o->can_0x737_MDU_Debug_4.MDU_Id_request = in;
	return 0;
}

int decode_can_0x737_MDU_uq_measured(const can_obj_mdu_v002x_tb_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x737_MDU_Debug_4.MDU_uq_measured);
	rval *= 0.02;
	if ((rval >= -655.35) && (rval <= 655.34)) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x737_MDU_uq_measured(can_obj_mdu_v002x_tb_h_t *o, double in) {
	assert(o);
	o->can_0x737_MDU_Debug_4.MDU_uq_measured = 0;
	if (in < -655.35)
		return -1;
	if (in > 655.34)
		return -1;
	in *= 50;
	o->can_0x737_MDU_Debug_4.MDU_uq_measured = in;
	return 0;
}

int decode_can_0x737_MDU_uq_request(const can_obj_mdu_v002x_tb_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x737_MDU_Debug_4.MDU_uq_request);
	rval *= 0.02;
	if ((rval >= -655.35) && (rval <= 655.34)) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x737_MDU_uq_request(can_obj_mdu_v002x_tb_h_t *o, double in) {
	assert(o);
	o->can_0x737_MDU_Debug_4.MDU_uq_request = 0;
	if (in < -655.35)
		return -1;
	if (in > 655.34)
		return -1;
	in *= 50;
	o->can_0x737_MDU_Debug_4.MDU_uq_request = in;
	return 0;
}

int print_can_0x737_MDU_Debug_4(const can_obj_mdu_v002x_tb_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "MDU_Id_measured = (wire: %.0f)\n", (double)(o->can_0x737_MDU_Debug_4.MDU_Id_measured)));
	r = print_helper(r, fprintf(output, "MDU_Id_request = (wire: %.0f)\n", (double)(o->can_0x737_MDU_Debug_4.MDU_Id_request)));
	r = print_helper(r, fprintf(output, "MDU_uq_measured = (wire: %.0f)\n", (double)(o->can_0x737_MDU_Debug_4.MDU_uq_measured)));
	r = print_helper(r, fprintf(output, "MDU_uq_request = (wire: %.0f)\n", (double)(o->can_0x737_MDU_Debug_4.MDU_uq_request)));
	return r;
}

static int pack_can_0x738_MDU_Debug_5(can_obj_mdu_v002x_tb_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t m = 0;
	/* MDU_u_mod: start-bit 23, length 16, endianess motorola, scaling 0.02, offset 0 */
	x = ((uint16_t)(o->can_0x738_MDU_Debug_5.MDU_u_mod)) & 0xffff;
	x <<= 32; 
	m |= x;
	/* MDU_ud_measured: start-bit 39, length 16, endianess motorola, scaling 0.02, offset 0 */
	x = ((uint16_t)(o->can_0x738_MDU_Debug_5.MDU_ud_measured)) & 0xffff;
	x <<= 16; 
	m |= x;
	/* MDU_ud_request: start-bit 55, length 16, endianess motorola, scaling 0.02, offset 0 */
	x = ((uint16_t)(o->can_0x738_MDU_Debug_5.MDU_ud_request)) & 0xffff;
	m |= x;
	/* MDU_power_calc: start-bit 6, length 15, endianess motorola, scaling 0.01, offset 0 */
	x = ((uint16_t)(o->can_0x738_MDU_Debug_5.MDU_power_calc)) & 0x7fff;
	x <<= 48; 
	m |= x;
	/* MDU_gate_fault: start-bit 7, length 1, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x738_MDU_Debug_5.MDU_gate_fault)) & 0x1;
	x <<= 63; 
	m |= x;
	*data = reverse_byte_order(m);
	o->can_0x738_MDU_Debug_5_tx = 1;
	return 8;
}

static int unpack_can_0x738_MDU_Debug_5(can_obj_mdu_v002x_tb_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t m = reverse_byte_order(data);
	if (dlc < 8)
		return -1;
	/* MDU_u_mod: start-bit 23, length 16, endianess motorola, scaling 0.02, offset 0 */
	x = (m >> 32) & 0xffff;
	o->can_0x738_MDU_Debug_5.MDU_u_mod = x;
	/* MDU_ud_measured: start-bit 39, length 16, endianess motorola, scaling 0.02, offset 0 */
	x = (m >> 16) & 0xffff;
	o->can_0x738_MDU_Debug_5.MDU_ud_measured = x;
	/* MDU_ud_request: start-bit 55, length 16, endianess motorola, scaling 0.02, offset 0 */
	x = m & 0xffff;
	o->can_0x738_MDU_Debug_5.MDU_ud_request = x;
	/* MDU_power_calc: start-bit 6, length 15, endianess motorola, scaling 0.01, offset 0 */
	x = (m >> 48) & 0x7fff;
	x = (x & 0x4000) ? (x | 0x8000) : x; 
	o->can_0x738_MDU_Debug_5.MDU_power_calc = x;
	/* MDU_gate_fault: start-bit 7, length 1, endianess motorola, scaling 1, offset 0 */
	x = (m >> 63) & 0x1;
	o->can_0x738_MDU_Debug_5.MDU_gate_fault = x;
	o->can_0x738_MDU_Debug_5_rx = 1;
	o->can_0x738_MDU_Debug_5_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x738_MDU_u_mod(const can_obj_mdu_v002x_tb_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x738_MDU_Debug_5.MDU_u_mod);
	rval *= 0.02;
	if ((rval >= -655.35) && (rval <= 655.34)) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x738_MDU_u_mod(can_obj_mdu_v002x_tb_h_t *o, double in) {
	assert(o);
	o->can_0x738_MDU_Debug_5.MDU_u_mod = 0;
	if (in < -655.35)
		return -1;
	if (in > 655.34)
		return -1;
	in *= 50;
	o->can_0x738_MDU_Debug_5.MDU_u_mod = in;
	return 0;
}

int decode_can_0x738_MDU_ud_measured(const can_obj_mdu_v002x_tb_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x738_MDU_Debug_5.MDU_ud_measured);
	rval *= 0.02;
	if ((rval >= -655.35) && (rval <= 655.34)) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x738_MDU_ud_measured(can_obj_mdu_v002x_tb_h_t *o, double in) {
	assert(o);
	o->can_0x738_MDU_Debug_5.MDU_ud_measured = 0;
	if (in < -655.35)
		return -1;
	if (in > 655.34)
		return -1;
	in *= 50;
	o->can_0x738_MDU_Debug_5.MDU_ud_measured = in;
	return 0;
}

int decode_can_0x738_MDU_ud_request(const can_obj_mdu_v002x_tb_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x738_MDU_Debug_5.MDU_ud_request);
	rval *= 0.02;
	if ((rval >= -655.35) && (rval <= 655.34)) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x738_MDU_ud_request(can_obj_mdu_v002x_tb_h_t *o, double in) {
	assert(o);
	o->can_0x738_MDU_Debug_5.MDU_ud_request = 0;
	if (in < -655.35)
		return -1;
	if (in > 655.34)
		return -1;
	in *= 50;
	o->can_0x738_MDU_Debug_5.MDU_ud_request = in;
	return 0;
}

int decode_can_0x738_MDU_power_calc(const can_obj_mdu_v002x_tb_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x738_MDU_Debug_5.MDU_power_calc);
	rval *= 0.01;
	if ((rval >= -110) && (rval <= 100)) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x738_MDU_power_calc(can_obj_mdu_v002x_tb_h_t *o, double in) {
	assert(o);
	o->can_0x738_MDU_Debug_5.MDU_power_calc = 0;
	if (in < -110)
		return -1;
	if (in > 100)
		return -1;
	in *= 100;
	o->can_0x738_MDU_Debug_5.MDU_power_calc = in;
	return 0;
}

int decode_can_0x738_MDU_gate_fault(const can_obj_mdu_v002x_tb_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x738_MDU_Debug_5.MDU_gate_fault);
	*out = rval;
	return 0;
}

int encode_can_0x738_MDU_gate_fault(can_obj_mdu_v002x_tb_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x738_MDU_Debug_5.MDU_gate_fault = in;
	return 0;
}

int print_can_0x738_MDU_Debug_5(const can_obj_mdu_v002x_tb_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "MDU_u_mod = (wire: %.0f)\n", (double)(o->can_0x738_MDU_Debug_5.MDU_u_mod)));
	r = print_helper(r, fprintf(output, "MDU_ud_measured = (wire: %.0f)\n", (double)(o->can_0x738_MDU_Debug_5.MDU_ud_measured)));
	r = print_helper(r, fprintf(output, "MDU_ud_request = (wire: %.0f)\n", (double)(o->can_0x738_MDU_Debug_5.MDU_ud_request)));
	r = print_helper(r, fprintf(output, "MDU_power_calc = (wire: %.0f)\n", (double)(o->can_0x738_MDU_Debug_5.MDU_power_calc)));
	r = print_helper(r, fprintf(output, "MDU_gate_fault = (wire: %.0f)\n", (double)(o->can_0x738_MDU_Debug_5.MDU_gate_fault)));
	return r;
}

static int pack_can_0x7d0_TB_Request(can_obj_mdu_v002x_tb_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* TB_Request_Speed: start-bit 0, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x7d0_TB_Request.TB_Request_Speed)) & 0xffff;
	i |= x;
	*data = (i);
	o->can_0x7d0_TB_Request_tx = 1;
	return 2;
}

static int unpack_can_0x7d0_TB_Request(can_obj_mdu_v002x_tb_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 2)
		return -1;
	/* TB_Request_Speed: start-bit 0, length 16, endianess intel, scaling 1, offset 0 */
	x = i & 0xffff;
	o->can_0x7d0_TB_Request.TB_Request_Speed = x;
	o->can_0x7d0_TB_Request_rx = 1;
	o->can_0x7d0_TB_Request_time_stamp_rx = time_stamp;
	return 2;
}

int decode_can_0x7d0_TB_Request_Speed(const can_obj_mdu_v002x_tb_h_t *o, int16_t *out) {
	assert(o);
	assert(out);
	int16_t rval = (int16_t)(o->can_0x7d0_TB_Request.TB_Request_Speed);
	*out = rval;
	return 0;
}

int encode_can_0x7d0_TB_Request_Speed(can_obj_mdu_v002x_tb_h_t *o, int16_t in) {
	assert(o);
	o->can_0x7d0_TB_Request.TB_Request_Speed = in;
	return 0;
}

int print_can_0x7d0_TB_Request(const can_obj_mdu_v002x_tb_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "TB_Request_Speed = (wire: %.0f)\n", (double)(o->can_0x7d0_TB_Request.TB_Request_Speed)));
	return r;
}

int unpack_message(can_obj_mdu_v002x_tb_h_t *o, const unsigned long id, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(id < (1ul << 29)); /* 29-bit CAN ID is largest possible */
	assert(dlc <= 8);         /* Maximum of 8 bytes in a CAN packet */
	switch (id) {
	case 0x109: return unpack_can_0x109_VCU_Engine_Torque_EPP(o, data, dlc, time_stamp);
	case 0x11a: return unpack_can_0x11a_MDU_Speed_Torque_Info(o, data, dlc, time_stamp);
	case 0x11b: return unpack_can_0x11b_MDU_Status_Info_1(o, data, dlc, time_stamp);
	case 0x11f: return unpack_can_0x11f_VCU_EPP_Data(o, data, dlc, time_stamp);
	case 0x152: return unpack_can_0x152_BMS_Pack_CV_Info(o, data, dlc, time_stamp);
	case 0x260: return unpack_can_0x260_MDU_Status_Info_2(o, data, dlc, time_stamp);
	case 0x55a: return unpack_can_0x55a_DASH_Bike_Info(o, data, dlc, time_stamp);
	case 0x580: return unpack_can_0x580_VCU_Vehicle_Info(o, data, dlc, time_stamp);
	case 0x734: return unpack_can_0x734_MDU_Debug_1(o, data, dlc, time_stamp);
	case 0x735: return unpack_can_0x735_MDU_Debug_2(o, data, dlc, time_stamp);
	case 0x736: return unpack_can_0x736_MDU_Debug_3(o, data, dlc, time_stamp);
	case 0x737: return unpack_can_0x737_MDU_Debug_4(o, data, dlc, time_stamp);
	case 0x738: return unpack_can_0x738_MDU_Debug_5(o, data, dlc, time_stamp);
	case 0x7d0: return unpack_can_0x7d0_TB_Request(o, data, dlc, time_stamp);
	default: break; 
	}
	return -1; 
}

int pack_message(can_obj_mdu_v002x_tb_h_t *o, const unsigned long id, uint64_t *data) {
	assert(o);
	assert(id < (1ul << 29)); /* 29-bit CAN ID is largest possible */
	switch (id) {
	case 0x109: return pack_can_0x109_VCU_Engine_Torque_EPP(o, data);
	case 0x11a: return pack_can_0x11a_MDU_Speed_Torque_Info(o, data);
	case 0x11b: return pack_can_0x11b_MDU_Status_Info_1(o, data);
	case 0x11f: return pack_can_0x11f_VCU_EPP_Data(o, data);
	case 0x152: return pack_can_0x152_BMS_Pack_CV_Info(o, data);
	case 0x260: return pack_can_0x260_MDU_Status_Info_2(o, data);
	case 0x55a: return pack_can_0x55a_DASH_Bike_Info(o, data);
	case 0x580: return pack_can_0x580_VCU_Vehicle_Info(o, data);
	case 0x734: return pack_can_0x734_MDU_Debug_1(o, data);
	case 0x735: return pack_can_0x735_MDU_Debug_2(o, data);
	case 0x736: return pack_can_0x736_MDU_Debug_3(o, data);
	case 0x737: return pack_can_0x737_MDU_Debug_4(o, data);
	case 0x738: return pack_can_0x738_MDU_Debug_5(o, data);
	case 0x7d0: return pack_can_0x7d0_TB_Request(o, data);
	default: break; 
	}
	return -1; 
}

int print_message(const can_obj_mdu_v002x_tb_h_t *o, const unsigned long id, FILE *output) {
	assert(o);
	assert(id < (1ul << 29)); /* 29-bit CAN ID is largest possible */
	assert(output);
	switch (id) {
	case 0x109: return print_can_0x109_VCU_Engine_Torque_EPP(o, output);
	case 0x11a: return print_can_0x11a_MDU_Speed_Torque_Info(o, output);
	case 0x11b: return print_can_0x11b_MDU_Status_Info_1(o, output);
	case 0x11f: return print_can_0x11f_VCU_EPP_Data(o, output);
	case 0x152: return print_can_0x152_BMS_Pack_CV_Info(o, output);
	case 0x260: return print_can_0x260_MDU_Status_Info_2(o, output);
	case 0x55a: return print_can_0x55a_DASH_Bike_Info(o, output);
	case 0x580: return print_can_0x580_VCU_Vehicle_Info(o, output);
	case 0x734: return print_can_0x734_MDU_Debug_1(o, output);
	case 0x735: return print_can_0x735_MDU_Debug_2(o, output);
	case 0x736: return print_can_0x736_MDU_Debug_3(o, output);
	case 0x737: return print_can_0x737_MDU_Debug_4(o, output);
	case 0x738: return print_can_0x738_MDU_Debug_5(o, output);
	case 0x7d0: return print_can_0x7d0_TB_Request(o, output);
	default: break; 
	}
	return -1; 
}

